package com.xtensus.xteldap.domain;

// Generated 6 ao�t 2013 15:04:19 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import jakarta.persistence.*;

/**
 * Categoriesprojet generated by hbm2java
 */
@Entity
@Table(name = "categoriesprojet")
public class Categoriesprojet extends Entite  implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -102579463788626212L;
	private Long categoriesProjetId;
	private String categoriesProjetLibelle;
	private String categoriesProjetDescription;

	public Categoriesprojet() {
	}

	public Categoriesprojet(
			String categoriesProjetLibelle,
			String categoriesProjetDescription) {
		this.categoriesProjetLibelle = categoriesProjetLibelle;
		this.categoriesProjetDescription = categoriesProjetDescription;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "categoriesProjetId", unique = true, nullable = false)
	public Long getCategoriesProjetId() {
		return this.categoriesProjetId;
	}

	public void setCategoriesProjetId(Long categoriesProjetId) {
		this.categoriesProjetId = categoriesProjetId;
	}

	@Column(name = "categoriesProjetLibelle", length = 50)
	public String getCategoriesProjetLibelle() {
		return this.categoriesProjetLibelle;
	}

	public void setCategoriesProjetLibelle(String categoriesProjetLibelle) {
		this.categoriesProjetLibelle = categoriesProjetLibelle;
	}

	@Column(name = "categoriesProjetDescription", length = 65535)
	public String getCategoriesProjetDescription() {
		return this.categoriesProjetDescription;
	}

	public void setCategoriesProjetDescription(
			String categoriesProjetDescription) {
		this.categoriesProjetDescription = categoriesProjetDescription;
	}
	
}
