package com.xtensus.xteldap.domain;

// Generated 6 ao�t 2013 15:04:19 by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.*;

/**
 * CriterescategoriesprojetId generated by hbm2java
 */
@Embeddable
public class CriterescategoriesprojetId extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 2247829873983822350L;
	private long criteresId;
	private long categoriesProjetId;

	public CriterescategoriesprojetId() {
	}

	public CriterescategoriesprojetId(long criteresId, long categoriesProjetId) {
		this.criteresId = criteresId;
		this.categoriesProjetId = categoriesProjetId;
	}

	@Column(name = "criteresId", nullable = false)
	public long getCriteresId() {
		return this.criteresId;
	}

	public void setCriteresId(long criteresId) {
		this.criteresId = criteresId;
	}

	@Column(name = "categoriesProjetId", nullable = false)
	public long getCategoriesProjetId() {
		return this.categoriesProjetId;
	}

	public void setCategoriesProjetId(long categoriesProjetId) {
		this.categoriesProjetId = categoriesProjetId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CriterescategoriesprojetId))
			return false;
		CriterescategoriesprojetId castOther = (CriterescategoriesprojetId) other;

		return (this.getCriteresId() == castOther.getCriteresId())
				&& (this.getCategoriesProjetId() == castOther
						.getCategoriesProjetId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCriteresId();
		result = 37 * result + (int) this.getCategoriesProjetId();
		return result;
	}

}
