package com.xtensus.xteldap.domain;

// Generated 6 ao�t 2013 15:04:19 by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.*;

/**
 * CriterescahierclausesadministrativesId generated by hbm2java
 */
@Embeddable
public class CriterescahierclausesadministrativesId extends Entite implements
		java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 6295292554107218015L;
	private long cahierClausesAdministrativesId;
	private long criteresId;

	public CriterescahierclausesadministrativesId() {
	}

	public CriterescahierclausesadministrativesId(
			long cahierClausesAdministrativesId, long criteresId) {
		this.cahierClausesAdministrativesId = cahierClausesAdministrativesId;
		this.criteresId = criteresId;
	}

	@Column(name = "cahierClausesAdministrativesId", nullable = false)
	public long getCahierClausesAdministrativesId() {
		return this.cahierClausesAdministrativesId;
	}

	public void setCahierClausesAdministrativesId(
			long cahierClausesAdministrativesId) {
		this.cahierClausesAdministrativesId = cahierClausesAdministrativesId;
	}

	@Column(name = "criteresId", nullable = false)
	public long getCriteresId() {
		return this.criteresId;
	}

	public void setCriteresId(long criteresId) {
		this.criteresId = criteresId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof CriterescahierclausesadministrativesId))
			return false;
		CriterescahierclausesadministrativesId castOther = (CriterescahierclausesadministrativesId) other;

		return (this.getCahierClausesAdministrativesId() == castOther
				.getCahierClausesAdministrativesId())
				&& (this.getCriteresId() == castOther.getCriteresId());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCahierClausesAdministrativesId();
		result = 37 * result + (int) this.getCriteresId();
		return result;
	}

}
