package com.xtensus.xteldap.domain;

// Generated 30 juil. 2013 11:40:13 by Hibernate Tools 3.4.0.CR1

import jakarta.persistence.*;
/**
 * Criterescategoriesprojettype generated by hbm2java
 */
@Entity
@Table(name = "criterescategoriesprojettype")
public class Criterescategoriesprojettype extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 9088256550642123356L;
	private CriterescategoriesprojettypeId id;
	private Criterestype criterestype;
	private Categoriesprojet categoriesprojettype;

	public Criterescategoriesprojettype() {
	}

	public Criterescategoriesprojettype(CriterescategoriesprojettypeId id,
			Criterestype criterestype, Categoriesprojet categoriesprojettype) {
		this.id = id;
		this.criterestype = criterestype;
		this.categoriesprojettype = categoriesprojettype;
	}

	@EmbeddedId
	@AttributeOverrides({
			@AttributeOverride(name = "criteresId", column = @Column(name = "criteresId", nullable = false)),
			@AttributeOverride(name = "categoriesProjetId", column = @Column(name = "categoriesProjetId", nullable = false)) })
	public CriterescategoriesprojettypeId getId() {
		return this.id;
	}

	public void setId(CriterescategoriesprojettypeId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "criteresId", nullable = false, insertable = false, updatable = false)
	public Criterestype getCriterestype() {
		return this.criterestype;
	}

	public void setCriterestype(Criterestype criterestype) {
		this.criterestype = criterestype;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "categoriesProjetId", nullable = false, insertable = false, updatable = false)
	public Categoriesprojet getCategoriesprojettype() {
		return this.categoriesprojettype;
	}

	public void setCategoriesprojettype(
			Categoriesprojet categoriesprojettype) {
		this.categoriesprojettype = categoriesprojettype;
	}

}
