# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ZDZmM2JkMTEwZDA0Yzk2OTJhNzBmOGE3ODk1M2QwNzEyZjM1OWNkZWJjNTRlZThkMzYxZTllYmRiN2NlYWMxNzZkMWFjOWYxNTBhYjUxZjE1M2I2Yzc1MDkzYWViZjE4MGNlZDIzNjY4ZGM2NmFmMzAzZjU5MTRhMDVkNWQzMzE=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
